- hosts: workers
  become: yes
  become_user: ubuntu
  become_method: sudo
  gather_facts: True

  tasks:
    - name: Start yarn
      command: '{{ item }}'
      with_items:
        - "nohup /usr/local/hadoop/bin/yarn --daemon start nodemanager"
